# Generated by Django 4.2.11 on 2024-08-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='socialmediaaccount',
            name='updated_at',
        ),
    ]
